### ISSUE TITLE
FAQ Request

### ISSUE THREAD

**Issue by parimatrix** [activescott/python-package-example#2]
Cheers! Helped me get an idea about the python packaging.

I have a query. Would be great if we could answer that here! Thanks!

Suppose
I create a folder: `python-package-example/package-project/src/boopackage/xyz`
I create a python file in folder xyz: `test_xyz.py`

How do I import a function from `boomodule.py`?
Thanks!

**Comment by activescott** [comment]
@parimatrix I actually didn't mean to close, this but I did add an example with some documentation on how to do this. See https://github.com/activescott/python-package-example/blob/95abc8ce37153dc4ec5c65c089b13d2518d5d5e8/package-project/src/boopackage/boomodule.py#L2 through https://github.com/activescott/python-package-example/blob/95abc8ce37153dc4ec5c65c089b13d2518d5d5e8/package-project/src/boopackage/boomodule.py#L4
